### ISSUE TITLE
Potential dependency conflicts between aceql and requests

### ISSUE THREAD

**Issue by NeolithEra** [kawansoft/aceql-http-client-python#2]
Hi, as shown in the following full dependency graph of  **_aceql_**, **_aceql_** requires **_requests *_**， while the installed version of **_requests-toolbelt_**(0.9.1) requires _**requests >=2.0.1,<3.0.0**_.

According to Pip's _“first found wins”_ installation strategy, _**requests 2.22.0**_ is the actually installed version.  

Although the first found package version _**requests 2.22.0**_ just satisfies the later dependency constraint （_**requests  >=2.0.1,<3.0.0**_), it will lead to a build failure once developers release a newer version of **_requests_**.

### Dependency tree--------
```
aceql - 2.0.0
| +- pytz(install version:2019.3 version range:>=2017.3)
| +- requests(install version:2.22.0 version range:>=2.18.4)
| | +- certifi(install version:2019.11.28 version range:>=2017.4.17)
| | +- chardet(install version:3.0.4 version range:<3.1.0,>=3.0.2)
| | +- idna(install version:2.8 version range:>=2.5,<2.9)
| | +- urllib3(install version:1.25.7 version range:<1.26,>=1.21.1)
| +- requests-toolbelt(install version:0.9.1 version range:>=0.8.0)
| | +- requests(install version:2.22.0 version range:>=2.0.1,<3.0.0)
| | | +- certifi(install version:2019.11.28 version range:>=2017.4.17)
| | | +- chardet(install version:3.0.4 version range:<3.1.0,>=3.0.2)
| | | +- idna(install version:2.8 version range:>=2.5,<2.9)
| | | +- urllib3(install version:1.25.7 version range:<1.26,>=1.21.1) 
```

Thanks for your attention.
Best,
Neolith

**Comment by NeolithEra** [comment]
### Solution

Fix your direct dependencies to be **_requests >=2.18.4, <3.0.0_** to remove this conflict. I have checked this revision will not affect your downstream projects now.

@ndepomereu May I pull a request to solve this issue?

**Comment by ndepomereu** [comment]
Hi,

Yes, you may pull a request.

Nicolas

Le lun. 23 déc. 2019 à 13:38, NeolithEra <notifications@github.com> a
écrit :

**Comment by ndepomereu** [comment]
Yes @NeolithEra  you are welcome to pull a request.



*From:* NeolithEra <notifications@github.com>
*Sent:* Monday, December 23, 2019 1:39 PM
*To:* kawansoft/aceql-http-client-python <
aceql-http-client-python@noreply.github.com>
*Cc:* Nicolas de Pomereu <ndepomereu@kawansoft.com>; Mention <
mention@noreply.github.com>
*Subject:* Re: [kawansoft/aceql-http-client-python] Potential dependency
conflicts between aceql and requests (#2)


Solution

Fix your direct dependencies to be *requests >=2.18.4, <3.0.0* to remove
this conflict. I have checked this revision will not affect your downstream
projects now.

@ndepomereu <https://github.com/ndepomereu> May I pull a request to solve
this issue?

—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub
<https://github.com/kawansoft/aceql-http-client-python/issues/2?email_source=notifications&email_token=ADQ7CVWPPALVOYVBYLBWF5LQ2CWODA5CNFSM4J6TVS6KYY3PNVWWK3TUL52HS4DFVREXG43VMVBW63LNMVXHJKTDN5WW2ZLOORPWSZGOEHRBIMQ#issuecomment-568464434>,
or unsubscribe

**Comment by ndepomereu** [comment]
version 2.0.1 fixes the problem. Thanks for input.
